language: python
python:
- 3.5
- 3.8
sudo: false
cache: pip
install:
- make ci_requirements
- pip install -U pip wheel codecov
script:
- make validate_translations
- make validate
after_success:
- codecov
